In [1]:
import math
import numpy as np
import mxnet as mx
from mxnet import nd

In [2]:
nd.array([[1, 2, 3], [5, 6, 7]])


[[1. 2. 3.]
 [5. 6. 7.]]
<NDArray 2x3 @cpu(0)>

In [3]:
x = nd.ones([2, 3])
x


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [4]:
y = nd.random.uniform(-1, 1, [2, 3])
y


[[0.09762704 0.18568921 0.43037868]
 [0.6885315  0.20552671 0.71589124]]
<NDArray 2x3 @cpu(0)>

In [5]:
x = nd.full([2, 3], 2.0)
x


[[2. 2. 2.]
 [2. 2. 2.]]
<NDArray 2x3 @cpu(0)>

In [6]:
x.shape, x.size, x.dtype

((2, 3), 6, numpy.float32)

In [7]:
# x = nd.full([2, 3], 2, dtype=np.float)
# x.shape, x.size, x.dtype

In [8]:
x, y

(
 [[2. 2. 2.]
  [2. 2. 2.]]
 <NDArray 2x3 @cpu(0)>,
 
 [[0.09762704 0.18568921 0.43037868]
  [0.6885315  0.20552671 0.71589124]]
 <NDArray 2x3 @cpu(0)>)

In [9]:
x * y


[[0.19525409 0.37137842 0.86075735]
 [1.377063   0.41105342 1.4317825 ]]
<NDArray 2x3 @cpu(0)>

In [10]:
y.exp(), x.exp(), math.e ** 2

(
 [[1.1025515 1.204048  1.5378398]
  [1.9907899 1.2281718 2.0460093]]
 <NDArray 2x3 @cpu(0)>,
 
 [[7.389056 7.389056 7.389056]
  [7.389056 7.389056 7.389056]]
 <NDArray 2x3 @cpu(0)>,
 7.3890560989306495)

In [11]:
nd.dot(x, y.T)


[[1.4273899 3.219899 ]
 [1.4273899 3.219899 ]]
<NDArray 2x2 @cpu(0)>

In [12]:
x.asnumpy() @ y.T.asnumpy()
# x @ y

array([[1.4273899, 3.219899 ],
       [1.4273899, 3.219899 ]], dtype=float32)

In [15]:
y, y[1, 2]

(
 [[0.09762704 0.18568921 0.43037868]
  [0.6885315  0.20552671 0.71589124]]
 <NDArray 2x3 @cpu(0)>,
 
 [0.71589124]
 <NDArray 1 @cpu(0)>)

In [18]:
y[:, 1:3]


[[0.18568921 0.43037868]
 [0.20552671 0.71589124]]
<NDArray 2x2 @cpu(0)>

In [19]:
y[:, 1:3] = 2
y


[[0.09762704 2.         2.        ]
 [0.6885315  2.         2.        ]]
<NDArray 2x3 @cpu(0)>

In [21]:
y[1:2, 0:2] = 4
y


[[0.09762704 2.         2.        ]
 [4.         4.         2.        ]]
<NDArray 2x3 @cpu(0)>

In [22]:
a = x.asnumpy()
type(a), a

(numpy.ndarray,
 array([[2., 2., 2.],
        [2., 2., 2.]], dtype=float32))

In [23]:
nd.array(a)


[[2. 2. 2.]
 [2. 2. 2.]]
<NDArray 2x3 @cpu(0)>